export enum LiveEventSubtype {
  LIVEEVENTSUBTYPE_NONE = 0,
  LIVEEVENTSUBTYPE_CARD_RED = 1,
  LIVEEVENTSUBTYPE_CARD_YELLOW = 2,
  LIVEEVENTSUBTYPE_CARD_YELLOW_RED = 3,
  LIVEEVENTSUBTYPE_GOAL_FREE_KICK = 4,
  LIVEEVENTSUBTYPE_GOAL_HEADER = 5,
  LIVEEVENTSUBTYPE_GOAL_OWN = 6,
  LIVEEVENTSUBTYPE_GOAL_PENALTY = 7,
  LIVEEVENTSUBTYPE_GOAL_REGULAR = 8,
}

export enum LiveEventType {
  LIVEEVENTTYPE_UNKNOWN = 0,
  LIVEEVENTTYPE_CARD = 1,
  LIVEEVENTTYPE_END_MATCH = 2,
  LIVEEVENTTYPE_EXTRA_MINUTE = 3,
  LIVEEVENTTYPE_GOAL = 4,
  LIVEEVENTTYPE_INJURY_TIMEOUT = 5,
  LIVEEVENTTYPE_PENALTY_MISSED = 6,
  LIVEEVENTTYPE_PERIOD_INFO = 7,
  LIVEEVENTTYPE_SHOT_BLOCKED = 8,
  LIVEEVENTTYPE_SHOT_OFF_TARGET = 9,
  LIVEEVENTTYPE_SHOT_ON_TARGET = 10,
  LIVEEVENTTYPE_START_MATCH = 11,
  LIVEEVENTTYPE_SUBSTITUTION = 12,
  LIVEEVENTTYPE_VIDEO_ASSISTANT_REFEREE = 13,
}
